import { createClient, SupabaseClient, User, Session } from '@supabase/supabase-js';
import { Vehicle, Lead, SiteSettings } from '../types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL?.trim() || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim() || '';

export const isSupabaseConfigured = (): boolean => {
  return Boolean(
    supabaseUrl &&
      supabaseAnonKey &&
      supabaseUrl !== 'MY_SUPABASE_URL' &&
      supabaseAnonKey !== 'MY_SUPABASE_ANON_KEY' &&
      supabaseUrl.startsWith('http')
  );
};

// SECURITY NOTICE:
// Client uses ONLY the public anon key (VITE_SUPABASE_ANON_KEY).
// Service role keys or secret keys are NEVER used or stored on client-side.
export const supabase: SupabaseClient | null = isSupabaseConfigured()
  ? createClient(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : null;

export interface GetVehiclesResult {
  data: Vehicle[];
  error: string | null;
  tableMissing?: boolean;
}

export interface GetVehicleByIdResult {
  data: Vehicle | null;
  error: string | null;
  tableMissing?: boolean;
}

export interface AdminStats {
  totalVehicles: number;
  availableVehicles: number;
  soldVehicles: number;
  leadsThisWeek: number;
  totalLeads: number;
  paidLeads?: number;
}

/**
 * Check if the error indicates a missing table in Supabase (PostgREST PGRST205 or Postgres 42P01)
 */
export function isTableMissingError(error: any): boolean {
  if (!error) return false;
  const code = error.code || '';
  const msg = (error.message || '').toLowerCase();
  return (
    code === 'PGRST205' ||
    code === '42P01' ||
    msg.includes('schema cache') ||
    msg.includes('could not find the table') ||
    msg.includes('does not exist')
  );
}

// Complete SQL Migration and Strict RLS Security Setup for Supabase
export const SUPABASE_SQL_SETUP = `-- ==========================================================
-- AutoVentra: Production Schema & Strict RLS Security Setup
-- Paste & execute in Supabase Dashboard > SQL Editor > New Query
-- ==========================================================

-- 1. Create Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT NOT NULL,
  mileage TEXT NULL DEFAULT '',
  transmission TEXT NOT NULL DEFAULT 'Automatic',
  fuel_type TEXT NOT NULL DEFAULT 'Petrol',
  body_type TEXT NOT NULL DEFAULT 'SUV',
  condition TEXT NOT NULL DEFAULT 'Foreign Used',
  price NUMERIC NOT NULL,
  discount_price NUMERIC,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'sold', 'reserved')),
  is_featured BOOLEAN NOT NULL DEFAULT false,
  description TEXT NOT NULL DEFAULT '',
  photos TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Create Leads & Bookings Table
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE SET NULL,
  vehicle_name TEXT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  intent TEXT DEFAULT 'inquiry',
  lead_type TEXT DEFAULT 'test_drive',
  rental_vehicle TEXT,
  rental_days INT,
  start_date TEXT,
  end_date TEXT,
  amount NUMERIC,
  payment_status TEXT DEFAULT 'unpaid',
  preferred_date TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Create Site Settings Table (M-Pesa Paybill, Business Name, Instructions)
CREATE TABLE IF NOT EXISTS public.site_settings (
  id BIGINT PRIMARY KEY DEFAULT 1,
  paybill_number TEXT DEFAULT '',
  paybill_account_number TEXT DEFAULT '',
  business_name TEXT DEFAULT '',
  payment_instructions TEXT DEFAULT 'Pay via M-Pesa using the details above, then contact us on WhatsApp with your payment confirmation.',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Ensure default row exists for site_settings
INSERT INTO public.site_settings (id, paybill_number, paybill_account_number, business_name, payment_instructions)
VALUES (1, '', '', '', 'Pay via M-Pesa using the details above, then contact us on WhatsApp with your payment confirmation.')
ON CONFLICT (id) DO NOTHING;

-- 4. Enable Row Level Security (RLS) on all tables
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- 5. Strict Vehicles RLS Policies:
-- Anyone (public anon) can SELECT/view vehicles
DROP POLICY IF EXISTS "Public can view vehicles" ON public.vehicles;
CREATE POLICY "Public can view vehicles" ON public.vehicles
  FOR SELECT
  TO public
  USING (true);

-- ONLY authenticated admin can INSERT new vehicles
DROP POLICY IF EXISTS "Authenticated admin can insert vehicles" ON public.vehicles;
CREATE POLICY "Authenticated admin can insert vehicles" ON public.vehicles
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.role() = 'authenticated');

-- ONLY authenticated admin can UPDATE vehicles
DROP POLICY IF EXISTS "Authenticated admin can update vehicles" ON public.vehicles;
CREATE POLICY "Authenticated admin can update vehicles" ON public.vehicles
  FOR UPDATE
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ONLY authenticated admin can DELETE vehicles
DROP POLICY IF EXISTS "Authenticated admin can delete vehicles" ON public.vehicles;
CREATE POLICY "Authenticated admin can delete vehicles" ON public.vehicles
  FOR DELETE
  TO authenticated
  USING (auth.role() = 'authenticated');

-- 6. Strict Leads RLS Policies:
-- Public can INSERT inquiries/test-drive bookings
DROP POLICY IF EXISTS "Public can insert leads" ON public.leads;
CREATE POLICY "Public can insert leads" ON public.leads
  FOR INSERT
  TO public
  WITH CHECK (true);

-- ONLY authenticated admin can VIEW leads
DROP POLICY IF EXISTS "Authenticated admin can view leads" ON public.leads;
CREATE POLICY "Authenticated admin can view leads" ON public.leads
  FOR SELECT
  TO authenticated
  USING (auth.role() = 'authenticated');

-- ONLY authenticated admin can UPDATE leads (e.g. mark as paid)
DROP POLICY IF EXISTS "Authenticated admin can update leads" ON public.leads;
CREATE POLICY "Authenticated admin can update leads" ON public.leads
  FOR UPDATE
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ONLY authenticated admin can DELETE leads
DROP POLICY IF EXISTS "Authenticated admin can delete leads" ON public.leads;
CREATE POLICY "Authenticated admin can delete leads" ON public.leads
  FOR DELETE
  TO authenticated
  USING (auth.role() = 'authenticated');

-- 7. Strict Site Settings RLS Policies:
-- Anyone (public) can SELECT site settings
DROP POLICY IF EXISTS "Public can view site settings" ON public.site_settings;
CREATE POLICY "Public can view site settings" ON public.site_settings
  FOR SELECT
  TO public
  USING (true);

-- ONLY authenticated admin can UPDATE or INSERT site settings
DROP POLICY IF EXISTS "Authenticated admin can modify site settings" ON public.site_settings;
CREATE POLICY "Authenticated admin can modify site settings" ON public.site_settings
  FOR ALL
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- 8. Storage Bucket for Vehicle Photos (Public access + Authenticated upload)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'vehicle-photos',
  'vehicle-photos',
  true,
  52428800,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif']
)
ON CONFLICT (id) DO UPDATE SET 
  public = true,
  file_size_limit = 52428800,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'];

-- Public can view images in vehicle-photos
DROP POLICY IF EXISTS "Public vehicle photos view" ON storage.objects;
CREATE POLICY "Public vehicle photos view" ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'vehicle-photos');

-- Only authenticated admin can upload photos
DROP POLICY IF EXISTS "Authenticated admin upload vehicle photos" ON storage.objects;
CREATE POLICY "Authenticated admin upload vehicle photos" ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'vehicle-photos');

-- Authenticated admin can update vehicle photos
DROP POLICY IF EXISTS "Authenticated admin update vehicle photos" ON storage.objects;
CREATE POLICY "Authenticated admin update vehicle photos" ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (bucket_id = 'vehicle-photos')
  WITH CHECK (bucket_id = 'vehicle-photos');

-- Only authenticated admin can delete vehicle photos
DROP POLICY IF EXISTS "Authenticated admin delete vehicle photos" ON storage.objects;
CREATE POLICY "Authenticated admin delete vehicle photos" ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id = 'vehicle-photos');
`;

export const STORAGE_BUCKET_SQL = `-- AutoVentraMotors: Storage Bucket & RLS Setup
-- Run this in Supabase Dashboard -> SQL Editor if photo uploads report "Bucket not found" or "RLS rejected"

-- 1. Create or update the 'vehicle-photos' bucket with 50MB limit & image mime types
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'vehicle-photos',
  'vehicle-photos',
  true,
  52428800,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif']
)
ON CONFLICT (id) DO UPDATE SET 
  public = true,
  file_size_limit = 52428800,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'];

-- 2. Public can view/download images from vehicle-photos
DROP POLICY IF EXISTS "Public vehicle photos view" ON storage.objects;
CREATE POLICY "Public vehicle photos view" ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'vehicle-photos');

-- 3. Authenticated admin can upload photos
DROP POLICY IF EXISTS "Authenticated admin upload vehicle photos" ON storage.objects;
CREATE POLICY "Authenticated admin upload vehicle photos" ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'vehicle-photos');

-- 4. Authenticated admin can update photos
DROP POLICY IF EXISTS "Authenticated admin update vehicle photos" ON storage.objects;
CREATE POLICY "Authenticated admin update vehicle photos" ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (bucket_id = 'vehicle-photos')
  WITH CHECK (bucket_id = 'vehicle-photos');

-- 5. Authenticated admin can delete vehicle photos
DROP POLICY IF EXISTS "Authenticated admin delete vehicle photos" ON storage.objects;
CREATE POLICY "Authenticated admin delete vehicle photos" ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id = 'vehicle-photos');
`;

// ==========================================
// AUTHENTICATION (Supabase Auth - Admin Only)
// ==========================================

export async function adminSignIn(
  email: string,
  password: string
): Promise<{ user: User | null; session: Session | null; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return {
      user: null,
      session: null,
      error: 'Supabase credentials are not configured in environment',
    };
  }

  try {
    const { data, error } = await supabase.auth.signInWithPassword({
      email: email.trim(),
      password,
    });

    if (error) {
      return { user: null, session: null, error: error.message };
    }

    return { user: data.user, session: data.session, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Sign in failed';
    return { user: null, session: null, error: msg };
  }
}

export async function adminSignOut(): Promise<{ error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { error: null };
  }

  try {
    const { error } = await supabase.auth.signOut();
    if (error) return { error: error.message };
    return { error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Sign out failed';
    return { error: msg };
  }
}

export async function getAdminUser(): Promise<User | null> {
  if (!isSupabaseConfigured() || !supabase) return null;
  try {
    const { data } = await supabase.auth.getUser();
    return data.user || null;
  } catch {
    return null;
  }
}

export async function getAdminSession(): Promise<Session | null> {
  if (!isSupabaseConfigured() || !supabase) return null;
  try {
    const { data } = await supabase.auth.getSession();
    return data.session || null;
  } catch {
    return null;
  }
}

export function subscribeToAuth(
  callback: (session: Session | null, user: User | null) => void
) {
  if (!isSupabaseConfigured() || !supabase) {
    return () => {};
  }
  const { data } = supabase.auth.onAuthStateChange((_event, session) => {
    callback(session, session?.user || null);
  });
  return () => {
    data.subscription.unsubscribe();
  };
}

// ==========================================
// VEHICLES (Public Read & Admin CRUD)
// ==========================================

/**
 * Fetch all vehicles from Supabase
 */
export async function getVehicles(): Promise<GetVehiclesResult> {
  if (!isSupabaseConfigured() || !supabase) {
    return { data: [], error: 'SUPABASE_NOT_CONFIGURED' };
  }

  try {
    const { data, error } = await supabase
      .from('vehicles')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      if (isTableMissingError(error)) {
        console.warn(
          'Supabase connected, but "vehicles" table is not created yet. Please execute the database schema migration.'
        );
        return { data: [], error: 'TABLE_NOT_FOUND', tableMissing: true };
      }
      console.warn('Notice while querying Supabase vehicles:', error.message);
      return { data: [], error: error.message };
    }

    const normalized: Vehicle[] = (data || []).map((v) => ({
      ...v,
      photos: Array.isArray(v.photos) ? v.photos : [],
      price: Number(v.price) || 0,
      discount_price:
        v.discount_price !== null && v.discount_price !== undefined
          ? Number(v.discount_price)
          : null,
      is_featured: Boolean(v.is_featured),
    }));

    return { data: normalized, error: null, tableMissing: false };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Unknown database error';
    return { data: [], error: msg };
  }
}

/**
 * Fetch a single vehicle by ID
 */
export async function getVehicleById(
  id: string | number
): Promise<GetVehicleByIdResult> {
  if (!isSupabaseConfigured() || !supabase) {
    return { data: null, error: 'SUPABASE_NOT_CONFIGURED' };
  }

  try {
    const { data, error } = await supabase
      .from('vehicles')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      if (isTableMissingError(error)) {
        return { data: null, error: 'TABLE_NOT_FOUND', tableMissing: true };
      }
      console.warn(`Notice while querying vehicle ${id} from Supabase:`, error.message);
      return { data: null, error: error.message };
    }

    if (!data) {
      return { data: null, error: 'Vehicle not found' };
    }

    const normalized: Vehicle = {
      ...data,
      photos: Array.isArray(data.photos) ? data.photos : [],
      price: Number(data.price) || 0,
      discount_price:
        data.discount_price !== null && data.discount_price !== undefined
          ? Number(data.discount_price)
          : null,
      is_featured: Boolean(data.is_featured),
    };

    return { data: normalized, error: null, tableMissing: false };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Unknown database error';
    return { data: null, error: msg };
  }
}

/**
 * Admin: Insert a new vehicle into the database
 */
export async function insertVehicle(
  vehicle: Omit<Vehicle, 'id' | 'created_at'>
): Promise<{ success: boolean; data?: Vehicle; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { success: false, error: 'Supabase is not configured' };
  }

  try {
    const payload = {
      make: vehicle.make.trim(),
      model: vehicle.model.trim(),
      year: Number(vehicle.year),
      mileage: vehicle.mileage ? String(vehicle.mileage).trim() : '',
      transmission: vehicle.transmission || 'Automatic',
      fuel_type: vehicle.fuel_type || 'Petrol',
      body_type: vehicle.body_type || 'SUV',
      condition: vehicle.condition || 'Foreign Used',
      price: Number(vehicle.price),
      discount_price:
        vehicle.discount_price !== null &&
        vehicle.discount_price !== undefined &&
        Number(vehicle.discount_price) > 0
          ? Number(vehicle.discount_price)
          : null,
      status: vehicle.status || 'available',
      is_featured: Boolean(vehicle.is_featured),
      description: vehicle.description || '',
      photos: Array.isArray(vehicle.photos) ? vehicle.photos : [],
    };

    const { data, error } = await supabase
      .from('vehicles')
      .insert([payload])
      .select()
      .single();

    if (error) {
      console.error('Error inserting vehicle:', error);
      return { success: false, error: error.message };
    }

    const created: Vehicle = {
      ...data,
      photos: Array.isArray(data.photos) ? data.photos : [],
      price: Number(data.price) || 0,
      discount_price: data.discount_price ? Number(data.discount_price) : null,
      is_featured: Boolean(data.is_featured),
    };

    return { success: true, data: created, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to insert vehicle';
    return { success: false, error: msg };
  }
}

/**
 * Admin: Update an existing vehicle
 */
export async function updateVehicle(
  id: string | number,
  vehicle: Partial<Omit<Vehicle, 'id' | 'created_at'>>
): Promise<{ success: boolean; data?: Vehicle; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { success: false, error: 'Supabase is not configured' };
  }

  try {
    const payload: Record<string, any> = {};
    if (vehicle.make !== undefined) payload.make = vehicle.make.trim();
    if (vehicle.model !== undefined) payload.model = vehicle.model.trim();
    if (vehicle.year !== undefined) payload.year = Number(vehicle.year);
    if (vehicle.mileage !== undefined) {
      payload.mileage = vehicle.mileage ? String(vehicle.mileage).trim() : '';
    }
    if (vehicle.transmission !== undefined) payload.transmission = vehicle.transmission;
    if (vehicle.fuel_type !== undefined) payload.fuel_type = vehicle.fuel_type;
    if (vehicle.body_type !== undefined) payload.body_type = vehicle.body_type;
    if (vehicle.condition !== undefined) payload.condition = vehicle.condition;
    if (vehicle.price !== undefined) payload.price = Number(vehicle.price);
    if (vehicle.discount_price !== undefined) {
      payload.discount_price =
        vehicle.discount_price !== null && Number(vehicle.discount_price) > 0
          ? Number(vehicle.discount_price)
          : null;
    }
    if (vehicle.status !== undefined) payload.status = vehicle.status;
    if (vehicle.is_featured !== undefined) payload.is_featured = Boolean(vehicle.is_featured);
    if (vehicle.description !== undefined) payload.description = vehicle.description;
    if (vehicle.photos !== undefined) payload.photos = vehicle.photos;

    const { data, error } = await supabase
      .from('vehicles')
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error(`Error updating vehicle ${id}:`, error);
      return { success: false, error: error.message };
    }

    const updated: Vehicle = {
      ...data,
      photos: Array.isArray(data.photos) ? data.photos : [],
      price: Number(data.price) || 0,
      discount_price: data.discount_price ? Number(data.discount_price) : null,
      is_featured: Boolean(data.is_featured),
    };

    return { success: true, data: updated, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to update vehicle';
    return { success: false, error: msg };
  }
}

/**
 * Admin: Delete a vehicle
 */
export async function deleteVehicle(
  id: string | number
): Promise<{ success: boolean; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { success: false, error: 'Supabase is not configured' };
  }

  try {
    const { error } = await supabase.from('vehicles').delete().eq('id', id);
    if (error) {
      console.error(`Error deleting vehicle ${id}:`, error);
      return { success: false, error: error.message };
    }
    return { success: true, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to delete vehicle';
    return { success: false, error: msg };
  }
}

/**
 * Admin: Quick update vehicle status ('available' | 'sold' | 'reserved')
 */
export async function updateVehicleStatus(
  id: string | number,
  status: 'available' | 'sold' | 'reserved'
): Promise<{ success: boolean; error: string | null }> {
  return updateVehicle(id, { status });
}

/**
 * Admin: Quick toggle featured state
 */
export async function toggleVehicleFeatured(
  id: string | number,
  is_featured: boolean
): Promise<{ success: boolean; error: string | null }> {
  return updateVehicle(id, { is_featured });
}

// ==========================================
// LEADS & DASHBOARD STATS (Live Queries)
// ==========================================

/**
 * Insert a new test-drive, rental booking, or vehicle lead (Public)
 */
export async function createLead(
  lead: Omit<Lead, 'id' | 'created_at'>
): Promise<{ success: boolean; error: string | null; tableMissing?: boolean }> {
  if (!isSupabaseConfigured() || !supabase) {
    return {
      success: true,
      error: 'Supabase credentials pending — saved in session.',
    };
  }

  try {
    const payload: any = {
      name: lead.name,
      phone: lead.phone,
      notes: lead.notes || null,
      preferred_date: lead.preferred_date || null,
      vehicle_id: lead.vehicle_id || null,
      vehicle_name: lead.vehicle_name || null,
    };

    // Add optional fields if provided
    if (lead.intent) payload.intent = lead.intent;
    if (lead.email) payload.email = lead.email;
    if (lead.lead_type) payload.lead_type = lead.lead_type;
    if (lead.rental_vehicle) payload.rental_vehicle = lead.rental_vehicle;
    if (lead.rental_days) payload.rental_days = lead.rental_days;
    if (lead.start_date) payload.start_date = lead.start_date;
    if (lead.end_date) payload.end_date = lead.end_date;
    if (lead.amount) payload.amount = lead.amount;
    if (lead.payment_status) payload.payment_status = lead.payment_status;

    const { error } = await supabase.from('leads').insert([payload]);

    if (error) {
      if (isTableMissingError(error)) {
        return {
          success: false,
          error: 'The "leads" table does not exist in your Supabase database yet. Please run the SQL schema migration.',
          tableMissing: true,
        };
      }
      console.warn('Notice while inserting lead to Supabase:', error.message);
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to submit request';
    return { success: false, error: msg };
  }
}

/**
 * Admin: Fetch leads & bookings
 */
export async function getAdminLeads(limit = 100): Promise<{ data: Lead[]; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { data: [], error: 'SUPABASE_NOT_CONFIGURED' };
  }

  try {
    const { data, error } = await supabase
      .from('leads')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(limit);

    if (error) {
      return { data: [], error: error.message };
    }

    return { data: (data as Lead[]) || [], error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to fetch leads';
    return { data: [], error: msg };
  }
}

/**
 * Admin: Update lead payment status ('unpaid' | 'paid' | 'deposit_paid')
 */
export async function updateLeadPaymentStatus(
  id: string | number,
  payment_status: 'unpaid' | 'paid' | 'deposit_paid' | string
): Promise<{ success: boolean; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { success: false, error: 'SUPABASE_NOT_CONFIGURED' };
  }

  try {
    const { error } = await supabase
      .from('leads')
      .update({ payment_status })
      .eq('id', id);

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to update payment status';
    return { success: false, error: msg };
  }
}

/**
 * Admin: Delete a lead
 */
export async function deleteLead(
  id: string | number
): Promise<{ success: boolean; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { success: false, error: 'SUPABASE_NOT_CONFIGURED' };
  }

  try {
    const { error } = await supabase.from('leads').delete().eq('id', id);
    if (error) return { success: false, error: error.message };
    return { success: true, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to delete lead';
    return { success: false, error: msg };
  }
}

/**
 * Admin: Calculate real-time stats (Total vehicles, Leads this week, etc.)
 * Strictly returns 0 if empty, never fake numbers.
 */
export async function getAdminDashboardStats(): Promise<AdminStats> {
  const defaultStats: AdminStats = {
    totalVehicles: 0,
    availableVehicles: 0,
    soldVehicles: 0,
    leadsThisWeek: 0,
    totalLeads: 0,
    paidLeads: 0,
  };

  if (!isSupabaseConfigured() || !supabase) {
    return defaultStats;
  }

  try {
    // 1. Total vehicles and breakdown
    const { data: vehiclesData, error: vehErr } = await supabase
      .from('vehicles')
      .select('id, status');

    if (!vehErr && vehiclesData) {
      defaultStats.totalVehicles = vehiclesData.length;
      defaultStats.availableVehicles = vehiclesData.filter((v) => v.status === 'available').length;
      defaultStats.soldVehicles = vehiclesData.filter((v) => v.status === 'sold').length;
    }

    // 2. Total leads and leads this week
    const now = new Date();
    const day = now.getDay();
    const diffToMonday = now.getDate() - day + (day === 0 ? -6 : 1);
    const monday = new Date(now.setDate(diffToMonday));
    monday.setHours(0, 0, 0, 0);

    const { data: leadsData, error: leadsErr } = await supabase
      .from('leads')
      .select('id, created_at, payment_status');

    if (!leadsErr && leadsData) {
      defaultStats.totalLeads = leadsData.length;
      defaultStats.leadsThisWeek = leadsData.filter(
        (l) => l.created_at && new Date(l.created_at) >= monday
      ).length;
      defaultStats.paidLeads = leadsData.filter(
        (l) => l.payment_status === 'paid' || l.payment_status === 'deposit_paid'
      ).length;
    }

    return defaultStats;
  } catch {
    return defaultStats;
  }
}

// ==========================================
// SITE SETTINGS (M-Pesa Paybill, Account, Instructions)
// ==========================================

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  id: 1,
  paybill_number: '',
  paybill_account_number: '',
  business_name: '',
  payment_instructions: 'Pay via M-Pesa using the details above, then contact us on WhatsApp with your payment confirmation.',
};

/**
 * Fetch current Site Settings (Public/Admin)
 * Returns live Supabase values or empty defaults
 */
export async function getSiteSettings(): Promise<{ data: SiteSettings; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { data: DEFAULT_SITE_SETTINGS, error: 'SUPABASE_NOT_CONFIGURED' };
  }

  try {
    const { data, error } = await supabase
      .from('site_settings')
      .select('*')
      .order('id', { ascending: true })
      .limit(1)
      .maybeSingle();

    if (error) {
      if (isTableMissingError(error)) {
        return { data: DEFAULT_SITE_SETTINGS, error: null };
      }
      return { data: DEFAULT_SITE_SETTINGS, error: error.message };
    }

    if (!data) {
      return { data: DEFAULT_SITE_SETTINGS, error: null };
    }

    return {
      data: {
        id: data.id || 1,
        paybill_number: data.paybill_number || '',
        paybill_account_number: data.paybill_account_number || '',
        business_name: data.business_name || '',
        payment_instructions:
          data.payment_instructions ||
          DEFAULT_SITE_SETTINGS.payment_instructions,
        updated_at: data.updated_at,
      },
      error: null,
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to fetch site settings';
    return { data: DEFAULT_SITE_SETTINGS, error: msg };
  }
}

/**
 * Admin: Update Site Settings (Paybill, Account, Business Name, Instructions)
 */
export async function updateSiteSettings(
  settings: Partial<SiteSettings>
): Promise<{ success: boolean; data?: SiteSettings; error: string | null }> {
  if (!isSupabaseConfigured() || !supabase) {
    return { success: false, error: 'Supabase credentials are not configured.' };
  }

  try {
    const payload = {
      id: 1,
      paybill_number: settings.paybill_number ?? '',
      paybill_account_number: settings.paybill_account_number ?? '',
      business_name: settings.business_name ?? '',
      payment_instructions:
        settings.payment_instructions ??
        DEFAULT_SITE_SETTINGS.payment_instructions,
      updated_at: new Date().toISOString(),
    };

    const { data, error } = await supabase
      .from('site_settings')
      .upsert(payload, { onConflict: 'id' })
      .select()
      .single();

    if (error) {
      if (isTableMissingError(error)) {
        return {
          success: false,
          error:
            'The "site_settings" table does not exist in Supabase yet. Please run the SQL schema migration in the Security tab.',
        };
      }
      return { success: false, error: error.message };
    }

    return { success: true, data: data as SiteSettings, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed to update site settings';
    return { success: false, error: msg };
  }
}

// ==========================================
// STORAGE: Multiple Photo Upload
// ==========================================

/**
 * Upload an image file to Supabase Storage bucket 'vehicle-photos'
 * Returns the public URL of the uploaded image.
 */
export async function uploadVehiclePhoto(
  file: File
): Promise<{ url: string | null; error: string | null; errorCode?: string }> {
  if (!isSupabaseConfigured() || !supabase) {
    return {
      url: null,
      error: 'Supabase credentials are not configured in environment variables.',
      errorCode: 'SUPABASE_NOT_CONFIGURED',
    };
  }

  try {
    // 1. Verify authentication state
    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session?.user) {
      return {
        url: null,
        error:
          'Admin session expired or unauthenticated. Please log in again at /av-manage before uploading photos.',
        errorCode: 'UNAUTHENTICATED',
      };
    }

    const fileExt = file.name.split('.').pop()?.toLowerCase() || 'jpg';
    const cleanFileName = `${Date.now()}_${Math.random().toString(36).substring(2, 8)}.${fileExt}`;
    const filePath = `uploads/${cleanFileName}`;

    const { error: uploadError } = await supabase.storage
      .from('vehicle-photos')
      .upload(filePath, file, {
        cacheControl: '3600',
        upsert: false,
        contentType: file.type || 'image/jpeg',
      });

    if (uploadError) {
      console.error('Supabase Storage upload error details:', uploadError);
      const rawMsg = uploadError.message || String(uploadError);

      if (
        rawMsg.toLowerCase().includes('bucket not found') ||
        (uploadError as { statusCode?: string | number }).statusCode === '404' ||
        (uploadError as { statusCode?: string | number }).statusCode === 404
      ) {
        return {
          url: null,
          error:
            "Storage bucket 'vehicle-photos' does not exist in your Supabase project. Please create the 'vehicle-photos' public bucket in Supabase Storage or run the provided SQL setup script in your Supabase SQL Editor.",
          errorCode: 'BUCKET_NOT_FOUND',
        };
      }

      if (
        rawMsg.toLowerCase().includes('row-level security') ||
        rawMsg.toLowerCase().includes('violates') ||
        rawMsg.toLowerCase().includes('unauthorized') ||
        (uploadError as { statusCode?: string | number }).statusCode === '403' ||
        (uploadError as { statusCode?: string | number }).statusCode === 403
      ) {
        return {
          url: null,
          error:
            "Storage RLS Policy Error: 'storage.objects' rejected the upload. Please verify that your Supabase Storage policies allow authenticated users to INSERT into bucket 'vehicle-photos'.",
          errorCode: 'STORAGE_RLS_REJECTED',
        };
      }

      if (rawMsg.toLowerCase().includes('payload too large') || rawMsg.toLowerCase().includes('exceeded')) {
        return {
          url: null,
          error: `File size too large for Supabase storage limit: ${rawMsg}`,
          errorCode: 'FILE_TOO_LARGE',
        };
      }

      return {
        url: null,
        error: `Supabase Storage upload error: ${rawMsg}`,
        errorCode: 'STORAGE_UPLOAD_ERROR',
      };
    }

    const { data: publicData } = supabase.storage
      .from('vehicle-photos')
      .getPublicUrl(filePath);

    if (!publicData?.publicUrl) {
      return {
        url: null,
        error: 'Failed to retrieve public URL from Supabase Storage.',
        errorCode: 'PUBLIC_URL_FAILED',
      };
    }

    return { url: publicData.publicUrl, error: null };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Storage upload failed due to network error';
    console.error('Storage upload caught exception:', err);
    return { url: null, error: msg, errorCode: 'NETWORK_OR_RUNTIME_ERROR' };
  }
}
